name: Deploy site
on:
  push:
    branches: [master]
  schedule:
    - cron: '13 12 * * 0' # Sunday 12:13 UTC = Monday 00:13 (or 01:13 during DST) NZ time
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          version: '0.4.13'
          enable-cache: true
      - name: Build site
        run: uv run --locked choreworld.py generate --output html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          folder: html
          branch: gh-pages
