name: Deploy site
on:
  push:
    branches: [main]
  schedule:
    - cron: '13 12 * * 0' # Sunday 12:13 UTC = Monday 00:13 (or 01:13 during DST) NZ time
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.5.24'
          enable-cache: true
      - name: Build site
        run: uv run --locked choreworld.py generate --output html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: html
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
